// Effects are [schedule, budget, scope, quality, morale, stakeholders, risk]. Positive = metric rises
// (for risk, positive means MORE risk). No option is best on every metric.
const o = (label, fx, why) => ({ label, fx, why });
export const SCENARIOS = [
  { id: 's01', title: 'Scope Creep', concepts: ['scope', 'change'],
    text: 'The client asks for three extra features that were never in the original scope.',
    lesson: 'Treat every change as a mini-decision: estimate its impact first, then trade it against something.',
    options: [
      o('Accept all features immediately', [-12, -8, 10, -4, -6, 8, 8], 'The client is delighted, but the team absorbed extra work with no extra time or money.'),
      o('Reject the request', [2, 0, 0, 2, 2, -12, 2], 'The plan is protected, but the client feels unheard and trust drops.'),
      o('Negotiate a smaller change', [-3, -2, 4, 1, 1, 2, -2], 'A partial change protects capacity while addressing the core need. Some expectations stay unmet.'),
      o('Accept, but request more time and budget', [-4, -6, 8, 0, -1, 0, 2], 'Scope grows with a fair price tag, though the extra negotiation costs goodwill and time.')] },
  { id: 's02', title: 'Deadline Pressure', concepts: ['schedule', 'resource'],
    text: 'The project is behind schedule and the client refuses to move the deadline.',
    lesson: 'You can trade time for money, scope or people. Overtime borrows from the future.',
    options: [
      o('Add temporary resources', [6, -9, 0, -3, -2, 3, 4], 'Capacity rises, but onboarding drains the team and the budget.'),
      o('Reduce scope', [8, 2, -9, 3, 2, -6, -3], 'The date is achievable again, but the client gets less than planned.'),
      o('Ask the team to work overtime', [7, -4, 0, -6, -12, 4, 6], 'Quick gains now, paid for with morale, quality and burnout risk.'),
      o('Negotiate a revised deadline', [-5, 0, 0, 3, 3, -7, -2], 'The team gets breathing room, but the sponsor sees a slip.')] },
  { id: 's03', title: 'Team Conflict', concepts: ['conflict', 'comms'],
    text: 'Two senior developers disagree about the technical approach and it is slowing everyone down.',
    lesson: 'Facilitation costs a little time now and often saves much more later.',
    options: [
      o('Let them resolve it themselves', [-2, 0, 0, -3, -6, 0, 5], 'Autonomy is respected, but the stalemate drags on and the team picks sides.'),
      o('Choose one approach immediately', [3, 0, 0, -1, -7, 0, 3], 'Fast and clear, but one developer feels overruled.'),
      o('Facilitate a technical discussion', [-3, -1, 0, 4, 5, 0, -4], 'A shared decision improves buy-in and design quality, at the cost of a day.'),
      o('Ask an architect for input', [-2, -4, 0, 5, 1, 0, -5], 'Expert input strengthens the design but adds cost and a short delay.')] },
  { id: 's04', title: 'Budget Cut', concepts: ['cost', 'priority'],
    text: 'The sponsor announces a 15% budget reduction, effective immediately.',
    lesson: 'Money, scope and quality are linked. Decide which one you are willing to give up.',
    options: [
      o('Reduce scope', [3, 6, -10, 1, -2, -6, -2], 'The workload matches the budget, but stakeholders lose features.'),
      o('Reduce resources', [-6, 8, 0, -3, -8, -2, 6], 'Savings are real, but a smaller team faces the same work.'),
      o('Cut quality-related activities', [2, 6, 0, -12, -2, 0, 10], 'Looks cheap today; defects and risk will return with interest.'),
      o('Negotiate the budget', [-2, 3, 0, 0, 0, -4, 0], 'You recover part of the cut, but spend political capital.'),
      o('Reprioritize features', [0, 5, -4, 0, 1, -2, -2], 'Focusing on high-value work balances the loss without hurting the team.')] },
  { id: 's05', title: 'Critical Bug', concepts: ['quality', 'risk'],
    text: 'A major bug is found just before release. It affects a core user flow.',
    lesson: 'Quality failures are risk decisions. Shipping a known defect transfers risk to users.',
    options: [
      o('Delay the release', [-10, -4, 0, 10, 2, -6, -8], 'The product is safer, but the date slips and the sponsor is unhappy.'),
      o('Release with the known issue', [4, 0, 0, -12, -3, -4, 12], 'The date holds, but users hit the bug and risk climbs.'),
      o('Remove the affected feature', [2, 0, -10, 4, 0, -5, -2], 'A stable release with less functionality.'),
      o('Add emergency resources', [-2, -8, 0, 7, -4, 2, -4], 'The bug is fixed fast, at a cost to budget and team energy.')] },
  { id: 's06', title: 'Stakeholder Changes Requirements', concepts: ['stakeholder', 'change'],
    text: 'A key stakeholder changes requirements halfway through the project.',
    lesson: 'A simple impact analysis turns an emotional request into a manageable trade-off.',
    options: [
      o('Accept the change fully', [-9, -6, 6, -3, -5, 7, 6], 'The stakeholder is happy; the plan is not.'),
      o('Run an impact analysis, then decide', [-3, -2, 2, 2, 0, 3, -3], 'A small delay buys an informed decision both sides understand.'),
      o('Refuse, citing the approved baseline', [1, 0, 0, 1, 2, -9, 1], 'The plan stays stable, but the relationship strains.'),
      o('Swap it for an equal-sized backlog item', [-2, 0, 1, 1, 0, 2, -1], 'Scope stays balanced and the stakeholder sees their change is taken seriously.')] },
  { id: 's07', title: 'Team Member Leaves', concepts: ['resource', 'risk'],
    text: 'A critical developer suddenly leaves the project.',
    lesson: 'Knowledge concentrated in one person is a risk. Replacements take time to become productive.',
    options: [
      o('Hire a replacement', [-7, -6, 0, -1, -2, 0, 3], 'Long-term fix, but recruiting and onboarding slow things down.'),
      o('Redistribute the work', [-5, 0, 0, -5, -8, 0, 6], 'No extra cost, but the team is stretched and knowledge gaps appear.'),
      o('Bring in a contractor', [-2, -7, 0, -2, 1, 0, 2], 'Fast help for a premium price.'),
      o('Reduce scope in that module', [3, 2, -7, 0, 1, -3, -3], 'Workload matches capacity, at the cost of functionality.')] },
  { id: 's08', title: 'Vendor Delay', concepts: ['risk', 'schedule'],
    text: 'An external vendor misses a key delivery that blocks integration work.',
    lesson: 'Dependencies you do not control need contingency plans before they fail.',
    options: [
      o('Wait for the vendor', [-9, 0, 0, 0, 0, -2, 6], 'No extra spend, but the delay cascades and risk grows.'),
      o('Switch to another vendor', [-4, -8, 0, -2, -1, 0, -2], 'Removes the dependency but costs money and rework.'),
      o('Build the component in-house', [-6, -6, 0, 2, -4, 0, 0], 'More control and quality, with real effort from your team.'),
      o('Mock the integration and continue', [3, 0, 0, -5, 0, 0, 6], 'Work continues, but you are building on assumptions.')] },
  { id: 's09', title: 'Security Vulnerability', concepts: ['risk', 'quality'],
    text: 'A security vulnerability is discovered shortly before launch.',
    lesson: 'Some risks have asymmetric downside. Mitigation effort should match potential impact.',
    options: [
      o('Fix it fully before launch', [-7, -4, 0, 8, -3, -2, -10], 'The safest path, but it pushes the date.'),
      o('Launch with mitigations and monitoring', [3, 0, 0, -4, 0, 2, 8], 'On time, but residual risk remains.'),
      o('Commission an external audit', [-5, -9, 0, 9, 0, -1, -9], 'High assurance at a high price in time and money.'),
      o('Patch quickly and review after launch', [2, -2, 0, -2, -2, 1, 4], 'A pragmatic compromise with some leftover exposure.')] },
  { id: 's10', title: 'Customer Feedback', concepts: ['agile', 'stakeholder'],
    text: 'Beta users dislike an important feature and say it is confusing.',
    lesson: 'Early feedback is cheap. Treat it as data rather than criticism.',
    options: [
      o('Rework the feature', [-8, -6, 2, 5, -3, 6, -2], 'Better fit for users, with real time and budget cost.'),
      o('Keep it and add guidance', [2, 0, 0, -1, 1, -5, 3], 'No delay, but the underlying problem remains.'),
      o('Make a quick usability tweak', [-3, -2, 0, 3, 0, 3, -1], 'A small, targeted fix that captures most of the benefit.'),
      o('Drop the feature', [3, 3, -8, 1, 0, -2, -2], 'Simplifies delivery, at the cost of capability.')] },
  { id: 's11', title: 'Team Burnout', concepts: ['resource', 'comms'],
    text: 'After weeks of pressure, the team is visibly exhausted and errors are increasing.',
    lesson: 'Sustainable pace is a delivery strategy. Exhausted teams produce defects and attrition.',
    options: [
      o('Pause and let the team recover', [-6, 0, 0, 3, 10, -2, -5], 'Energy returns, but the schedule loses time.'),
      o('Push through to the end', [4, 0, 0, -6, -12, 2, 10], 'Short-term speed with growing quality and attrition risk.'),
      o('Rebalance and reprioritize the workload', [-2, 0, -3, 1, 6, -2, -3], 'A middle path that lowers pressure by trimming lower-value work.'),
      o('Offer bonuses and perks', [1, -5, 0, 0, 5, 0, 2], 'Helps mood, but workload and fatigue remain unchanged.')] },
  { id: 's12', title: 'Final Release', concepts: ['risk', 'quality', 'stakeholder'],
    text: 'The project reaches the final stage. Decide how to launch.',
    lesson: 'Release decisions weigh readiness against commitments. Staged rollouts reduce the cost of being wrong.',
    options: [
      o('Launch on the planned date', [4, 0, 0, -4, -3, 4, 6], 'The commitment is honored, with some unpolished edges.'),
      o('Delay one week to polish', [-6, -3, 0, 7, 2, -3, -5], 'A cleaner product with a visible slip.'),
      o('Launch with reduced scope', [2, 1, -8, 3, 1, -3, -3], 'A focused, stable launch with deferred features.'),
      o('Roll out in phases', [-1, -2, -2, 3, 0, 1, -6], 'Limits exposure and gathers real feedback as you go.')] },
];
